application:
  name: "TView Feature Demos"
  enableMouse: true
  escapePassthroughPages: ["form"]
  globalKeyBindings:
    - key: "Escape"
      action: '{{ switchToPage "main" }}'
    - key: "Ctrl+C"
      action: '{{ stopApp }}'
    - key: "Ctrl+Q"
      action: '{{ stopApp }}'
  root:
    type: pages
    pages:
      - name: main
        ref: main.yaml
      - name: box
        ref: box.yaml
      - name: button
        ref: button.yaml
      - name: checkbox
        ref: checkbox.yaml
      - name: dropdown
        ref: dropdown.yaml
      - name: flex
        ref: flex.yaml
      - name: form
        ref: form.yaml
      - name: grid
        ref: grid.yaml
      - name: clock
        ref: clock.yaml
      - name: inputfield
        ref: inputfield.yaml
      - name: list
        ref: list.yaml
      - name: modal
        ref: modal.yaml
      - name: table
        ref: table.yaml
      - name: textview
        ref: textview.yaml
      - name: treeview
        ref: treeview.yaml
      - name: treeview-standalone
        ref: treeview-standalone.yaml
